# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuma-migrator" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "d830eb5a75a4b6f5273bd0ad192c8086d48dea876d852260d593513224fa9c96"
      url "https://github.com/Kong/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd74064252d5ca61e1eca92c554931aa0fba784e7e366cd9aba801a8c3acb429"
      url "https://github.com/Kong/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "807b5f7d02734d62169897a5d94678a0c466f05a127fffad1d7138cf13cd6d80"
      url "https://github.com/Kong/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8e05d1c6120f19db504138895879740c208fc48e56e737253b3d91faebb0b58"
      url "https://github.com/Kong/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kuma-migrator"
  desc "Migrate Kuma and Kong Mesh YAML policy manifests across all supported API versions"
  homepage "https://github.com/Kong/kuma-migrator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kuma-migrator"

  # No zap stanza required

end
