# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuma-migrator" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "053a3f6242043ca7944e87ee6e9e9ffe9760f54ccb853b73d73a21f122fac5c3"
      url "https://github.com/Kong/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc9887f35383057b5a6dd46ae21a798a40283ab69599ca13871ed60e73949dde"
      url "https://github.com/Kong/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aaf62533c483afd04d0c52c6169645e5a52da9875e2d6e09d3ed60cbdea1a025"
      url "https://github.com/Kong/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6fc473a40de3cf7500f22f33a204e51c16282e8f9e55cc9141d843938e08dd15"
      url "https://github.com/Kong/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kuma-migrator"
  desc "Migrate Kuma and Kong Mesh YAML policy manifests across all supported API versions"
  homepage "https://github.com/Kong/kuma-migrator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kuma-migrator"

  # No zap stanza required
end
