# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuma-migrator" do
  version "0.2.9"

  on_macos do
    on_intel do
      sha256 "7533ec6a02dbef92d6b4f3113d039f2617bea2cbae7361b73633d47b6a96eb39"
      url "https://github.com/bcollard/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8458e4e60e00a40f99f430c401e9f6e652235f85e3101fc9a04a3c1189ff27dc"
      url "https://github.com/bcollard/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e5c6d53f98c082f1b5eb627db5d5874b9b75a3163c893a388763be3a77a2d7d6"
      url "https://github.com/bcollard/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4fefd0d3a048ef19373053eff36cbf9906b60a9f667daf440d93be96fff92e90"
      url "https://github.com/bcollard/kuma-migrator/releases/download/v#{version}/kuma-migrator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kuma-migrator"
  desc "Migrate Kuma and Kong Mesh YAML policy manifests across all supported API versions"
  homepage "https://github.com/Kong/kuma-migrator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kuma-migrator"

  # No zap stanza required

end
